apiVersion: v1
kind: Service
metadata:
  name: cms-client-lb
  namespace: dorm  # Replace with your namespace if different
spec:
  selector:
    app: cms-client  # This should match the label on your cms-client pods
  ports:
    - protocol: TCP
      port: 8080        # External port that the LoadBalancer will expose
      targetPort: 4200 # Port on the cms-client pod that the service will forward traffic to
  type: LoadBalancer
