apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-service
  namespace: dorm
  labels:
    app: cms-service
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cms-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cms-service
        name: cms-service
    spec:
      containers:
        - name: cms-service
          image: "mahdimazaheri/cms_service:1.1.24"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 400M
              ephemeral-storage: 200M
            requests:
              cpu: 200m
              memory: 400M
              ephemeral-storage: 200M
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:123456@postgres-production-svc:5432/cms
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker-reg-89btsv1f
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
