
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-client
  namespace: dorm
  labels:
    app: cms-client
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cms-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cms-client
        name: cms-client
    spec:
      containers:
        - name: cms-client
          image: "docker.arvancloud.ir/mahdimazaheri/cms_client:1.1.31"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4200
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 200M
              ephemeral-storage: 300M
            requests:
              cpu: 100m
              memory: 200M
              ephemeral-storage: 300M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: cloud-container-g2
