apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongestoon-service
  namespace: dorm
  labels:
    app: dongestoon-service
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dongestoon-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dongestoon-service
        name: dongestoon-service
    spec:
      containers:
        - name: dongestoon-service
          image: "ghcr.io/dormsoftware/dongestoon_service:1.0.5"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 400M
              ephemeral-storage: 200M
            requests:
              cpu: 200m
              memory: 400M
              ephemeral-storage: 200M
          env:
            - name: ConnectionString
              value: "host=postgres-production-svc;port=5432;database=dongestoon;user=postgres;password=123456;include error detail=true"
            - name: SmtpServer
              value: smtp.gmail.com
            - name: RunMigrations
              value: "true"
            - name: SmtpPort
              value: "587"
            - name: Email
              value: dongestoon.dorm@gmail.com
            - name: EmailPassword
              value: jgih qxfp vufi nphv
            - name: SecretKey
              value: 4ccad75e927dbac7fbed22f66e883b762d0d216731e84361bc7ee1794a2825fb
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker-reg-89btsv1f
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
