apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-production-pvc
  namespace: dorm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-production-vol
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-production
  namespace: dorm
  labels:
    app: postgres-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-production
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-production
    spec:
      containers:
        - name: postgres-production
          image: postgres:15.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 800Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: 400m
              memory: 800Mi
              ephemeral-storage: 1Gi
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "123456"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-production-pvc
