apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-production-pvc
  namespace: dorm  # Adjust the namespace as needed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Match the storage class of PV
