apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-production
  namespace: dorm
  labels:
    app: postgres-production
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres-production
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-production
    spec:
      containers:
        - name: postgres-production
          image: postgres:15.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 800M
              ephemeral-storage: 1G
            requests:
              cpu: 400m
              memory: 800M
              ephemeral-storage: 1G
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "123456"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-production-vol
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgres-production-vol
          persistentVolumeClaim:
            claimName: postgres-production-vol
