apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-production-vol
spec:
  capacity:
    storage: 10Gi  # Set the storage size you need
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Use your cluster's storage class
  hostPath:  # Use hostPath for local storage (adjust as needed)
    path: /mnt/data/postgres